#!/usr/bin/env python3
"""
Publish pipeline artifacts from data/ to docs/data for GitHub Pages.
Standard library only; plain-text logging.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

SOURCE_DIR = Path("data")
DEST_DIR = Path("docs") / "data"
DOCS_ROOT = Path("docs")

# Files that must exist for the site to function
CRITICAL_FILES = [
    "court_docs_parsed.csv",
]

# Files that enhance the site but are optional
OPTIONAL_FILES = [
    "court_docs_audit.csv",
    "audit_results.json",
    "parse_report.json",
    "unknown_event_types.csv",
]

# Pages to copy (source -> destination) to ensure GitHub Pages has the HTML entry points.
PAGES_TO_COPY = [
    (Path("court-documents.html"), DOCS_ROOT / "dashboard.html"),
]


def generate_index_html(target_dir: Path) -> None:
    """Generate a default index.html with correct repo link if missing."""
    html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GARS Pipeline Dashboard</title>
    <link rel="stylesheet" href="css/6420-final.css">
    <style>
        body { font-family: sans-serif; margin: 2rem; background: #f4f4f9; }
        .container { max_width: 800px; margin: 0 auto; background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #e74c3c; padding-bottom: 0.5rem; }
        .card { background: #ecf0f1; padding: 1rem; margin-bottom: 1rem; border-radius: 4px; }
        a { color: #2980b9; text-decoration: none; font-weight: bold; }
        a:hover { text-decoration: underline; }
        .status { font-weight: bold; color: green; }
        .repo-link { font-size: 0.9rem; color: #7f8c8d; margin-left: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🏛️ Court Docs Pipeline</h1>
            <p>
                <strong>Status:</strong> <span class="status">● Live</span> |
                <strong>Agent:</strong> Builder
                <a href="https://github.com/katierock01/court-docs-pipeline" class="repo-link" target="_blank">View Repository ↗</a>
            </p>
        </header>
        <main>
            <div class="card">
                <h2>📊 Case Zero Status</h2>
                <p>Case ID: <code>2025-0000424475-GA</code></p>
                <ul>
                    <li><a href="data/court_docs_parsed.csv">📂 Download Parsed CSV</a></li>
                    <li><a href="dashboard.html">📄 Open Dashboard</a></li>
                </ul>
            </div>
            <div class="card">
                <h2>🛠️ System Artifacts</h2>
                <ul>
                    <li><a href="data/parse_report.json">Parse Report (JSON)</a></li>
                    <li><a href="data/audit_results.json">Audit Results (JSON)</a></li>
                    <li><a href="data/court_docs_audit.csv">Audit Results (CSV)</a></li>
                    <li><a href="data/unknown_event_types.csv">Unknown Event Types</a></li>
                </ul>
            </div>
        </main>
        <footer>
            <p><small>Generated by GARS Pipeline | Hosted on GitHub Pages</small></p>
        </footer>
    </div>
</body>
</html>
"""
    target_dir.mkdir(parents=True, exist_ok=True)
    with (target_dir / "index.html").open("w", encoding="utf-8") as f:
        f.write(html_content)
    print("   [OK] Generated default index.html with repo link to katierock01")


def main() -> int:
    if not DEST_DIR.exists():
        try:
            DEST_DIR.mkdir(parents=True, exist_ok=True)
            print(f"[INFO] Created directory: {DEST_DIR}")
        except OSError as e:
            print(f"[ERROR] Could not create directory {DEST_DIR}: {e}")
            return 1

    print(f"[INFO] Publishing data from '{SOURCE_DIR}' to '{DEST_DIR}'...")

    # Check critical files
    for filename in CRITICAL_FILES:
        src = SOURCE_DIR / filename
        if not src.exists():
            print(f"[ERROR] CRITICAL: {filename} is missing in source.")
            print("        Run the pipeline (parse_court_docs.py) first.")
            return 1

    all_files = CRITICAL_FILES + OPTIONAL_FILES
    copied_count = 0

    for filename in all_files:
        src = SOURCE_DIR / filename
        dst = DEST_DIR / filename
        if src.exists():
            try:
                shutil.copy2(src, dst)
                print(f"   [OK] Copied {filename}")
                copied_count += 1
            except Exception as e:
                print(f"   [ERROR] Failed to copy {filename}: {e}")
        else:
            if filename in OPTIONAL_FILES:
                print(f"   [WARN] Skipping {filename} (not found)")

    print(f"\n[DONE] {copied_count} files published to {DEST_DIR}.")
    # Copy dashboard HTML into docs/ for GitHub Pages
    for src, dst in PAGES_TO_COPY:
        if src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            try:
                shutil.copy2(src, dst)
                print(f"[OK] Copied page {src} -> {dst}")
            except Exception as e:
                print(f"[WARN] Failed to copy page {src}: {e}")
        else:
            print(f"[WARN] Page not found, skipping: {src}")

    # Generate a default landing page if missing
    index_path = DOCS_ROOT / "index.html"
    if not index_path.exists():
        generate_index_html(DOCS_ROOT)

    print("Ready to commit and push.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
